spring.application.name=medicineProject
spring.threads.virtual.enabled=true

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# mybatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# Jwt
jwt.secret=my-super-secret-key-for-jwt-project-2026-security
jwt.expiration=3600000

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tjdwns8083@gmail.com
spring.mail.password=pyin lunn gvgx rpky

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com